### ISSUE TITLE
好像没有将H264转换成cv::Mat

### ISSUE THREAD

**Issue by stronger1990** [hirorogithub/ffmpeg_sample-H264_to_cv-Mat#1]
你好，我看了一下你的代码，其实只要看了.java或jni就知道，输出并没有mat这个关键词，输入的是byte[]，输出的也是byte[]。或者是我理解错了？？？
你好，能否不借助ffmpeg，直接将H264转成mat？

**Comment by hirorogithub** [comment]
你好，其实mat的数据是在cpp层保存着，在decoder的有文件里有声明，如果你不需要java 你可以直接看这个有文件，有接口取mat数据的，java那边我只是把mat当作字节数组而已所以你看不到mat。。。。其实代码不是特别复杂，只要忽略实际解码的部分。。。其他都是简单地封装一下而已
至于h264直接转mat，我不知道你清不清楚h264和mat的关系，如果你知道了就当我好为人师吧：h264是一种视频的压缩编码，而mat其实是opencv里保存位图的数据结构，里面会一个一个像素保存图片。所以h264数据源转mat，首先你就绕不开视频解码，其次才是解码出来复杂的图像格式到mat的转换。而视频解码业界基本都在用ffmpeg的样子，至于有没有什么其他更简单方便的库，我不是特别清楚，如果你知道也请告诉我，因此我认为目前绕不开用ffMPEG解码视频
