### ISSUE TITLE
关于解视频流

### ISSUE THREAD

**Issue by joshua19881228** [hirorogithub/ffmpeg_sample-H264_to_cv-Mat#2]
您好，有个问题想请教一下。
我看您的代码里是一次性的读取了一个视频文件，然后对视频进行拆帧。我的问题是如果输入是一个h264的视频流该怎么处理呢？

**Comment by hirorogithub** [comment]
流式读取的话估计就要自己对输入流自己按照格式拆帧了，我当初是Android端发送264流的时候就已经拆好一帧一帧发送的了，估计还需要留意处理一下SPS,PPS那些特殊帧
